##################################
#         FakeDDoS plugin        #
#               by               #
#          SpaicyGaming          #
##################################

#This message will be displayed if a player use "/ddos"
NoArgsMessage: '&fUse /ddos [player]'

#To use /ddos command you need the permission "fakeddos.use"
NoDDoSPermissions: '&cSorry, you don''t have enough permissions.'
NoReloadPermissions: '&cSorry, you don''t have the permission ''fakeddos.reload''.'

#This message will be displayed if a player try to ddos himself
AutoDDoSMessage: '&cYou can''t DDoS &lyourself!'

#Title Editor       %SENDER = attacker
UnderAttacTitle: DDoS Attac!
UnderAttacSubtitle: From %SENDER

# %TARGET = player under ddos attac
SentDDoSMessage: 'You dossed %TARGET'
TargetOffline: '&cThe player &o"%TARGET"&r &cis not Online.'

Effects:
  Target:
    Sounds: true
    Particles: true
  Sender:
    Sounds: true
    Particles: true

#This message will be displayed if the console try to use /ddos command
OnlyPlayerCmd: This command can only be run by a player.
WrongCommand: '&cThis command does not exist. Please use &l/fakeddos.'
TooManyArgs: '&cToo many args.'

####DO NOT TOUCH###
ConfigVersion: 1.2
