##################################
#         FakeDDoS plugin        #
#               by               #
#          SpaicyGaming          #
##################################

#This message will be displayed if a player use "/ddos"
NoArgsMessage: Use /ddos [player]

#To use /ddos command you need the permission "fakeddos.use"
NoDDoSPermissions: Sorry, you don't have enough permissions.
NoReloadPermissions: Sorry, you don't have the permission 'fakeddos.reload'.

#This message will be displayed if a player try to ddos himself
AutoDDoSMessage: You can't DDoS yourself!

#Title Editor       %SENDER = attacker
UnderAttacTitle: DDoS Attac!
UnderAttacSubtitle: From %SENDER

# %TARGET = player under ddos attac
SentDDoSMessage: You dossed %TARGET
TargetOffline: The player "%TARGET" is not Online.

Effects:
  Target:
    Sounds: true
    Particles: true
  Sender:
    Sounds: true
    Particles: true

#This message will be displayed if the console try to use /ddos command
OnlyPlayerCmd: This command can only be run by a player.
WrongCommand: This command does not exist. Please use /fakeddos.
TooManyArgs: Too many args.

####DO NOT TOUCH###
ConfigVersion: 1.1
