main: io.github.spaicygaming.fakeddos.FakeDDoS

author: SpaicyGaming
name: FakeDDoS
version: 1.4

commands:
   ddos:
     description: FakeDDoS a player.
     
   fakeddos:
     description: Shows subcommands.